library("Cairo")
library("deSolve")
library("plotrix")
library("calibrate")
library("rgl")
library("rootSolve")
lplot <- function(x, y, col="black", xlab="", ylab="", lwd=2) {
  par(mar=c(3,4,2,2), cex.axis=2, cex.lab=2, mgp = c(3,2,0), las=1, lwd=1)
  xat <- pretty(x)
  yat <- pretty(y)
  plot(range(xat), range(yat), type="n", xlab="", ylab="", axes="F")
  lines(x, y, col=col, lwd=lwd)  
  axis(1, las=1, pos=0, at=xat)
  axis(2, las=1, pos=0, at=yat)
  mtext(xlab, side=1, cex=2, adj=1.05, padj=-1)
  mtext(ylab, side=2, cex=2, line=-1.2, padj=-11.5, las=1)
}