source("../Tools/Common.R")
source("Model.R")
load.input("./Runs/001/")
calc.default()

show.plot2d(d, c("time", "x"))
show.plot2d(d, c("time", "y"))
show.plot2d(d, c("time", "z"))
show.plot2d(d, c("time", "u"))
show.plot2d(d, c("time", "w"))
show.plot2d(d, c("time", "w"))
show.scatterplot3d(d, c("x", "y", "z"))
show.scatterplot3d(d, c("x", "u", "w"))

save.default()